ionelmc/pytest-benchmark

src/pytest_benchmark/pep418.py

Python 3 does not permit the usage of commas for binding exceptions to local variables in `except` blocks.

Fix python3 syntax error

---

src/pytest_benchmark/plugin.py

in particular, add the pypy version when on pypy, and the revision of the build, useful when comparing benchmarks against multiple versions of not-released-yet pypys :)

add more info to machine_info

---

CHANGELOG.rst
docs/usage.rst
setup.py
src/pytest_benchmark/fixture.py
src/pytest_benchmark/plugin.py
src/pytest_benchmark/stats.py
tests/test_benchmark.py

this is a *very* important info, as we want to avoid comparing against different CPUs :)

add more info about the actual CPU we used

---

src/pytest_benchmark/utils.py
tests/test_utils.py

this is needed especially in git where the branch is not permanentely part of the commit: if we don't record it here, the info is lost forever

record the branch of the commit;

---

AUTHORS.rst
CHANGELOG.rst
src/pytest_benchmark/histogram.py
src/pytest_benchmark/utils.py

PyGal made a change:
https://github.com/Kozea/pygal/commit/c7aefc39898dcc48f595b4bed372eebc1f28629e
This caused is_list_like to no longer be imported in pygal.graph.box.
pytest-benchmark should _not_ import this method from pygal. It comes
from their _compat module, which is considered private.

Fix histogram with latest PyGal version

---

src/pytest_benchmark/utils.py

Before, detecting whether tests are run in a git/hg versioned
project was only successful when running them from the root
directory.
This resulted in a "unversioned" commit_info.id.
This change fixes git/hg repo detection and properly sets the
commit_info.id even when running in a sub directory.

Fix git/hg detection in sub directories

---

AUTHORS.rst
CHANGELOG.rst
src/pytest_benchmark/cli.py
src/pytest_benchmark/plugin.py
src/pytest_benchmark/session.py
src/pytest_benchmark/storage/elasticsearch.py
src/pytest_benchmark/utils.py
tests/test_elasticsearch_storage.py

This is related to #72.
When using `--benchmark-storage` with elasticsearch feature pytest-benchmark prints the whole URL when saving the data after tests finished. If the URL contains credentials and if the results of the run are public, then the credentials are leaked. The first commit in this pull request addresses this issue by masking eventual credentials before printing the URL.
Note that this does not protect other leaks such as when using tox together with pytest, as tox will print the whole pytest command line before running it and leak credentials anyway. Our current workaround for this is to use CI environment variables to set the content of a `pytest.ini` file with the relevant options for pytest. Those options are not printed by tox because they are loaded by pytest itself. …

Hide creds when saving and use netrc file 

---

src/pytest_benchmark/utils.py

With git, there are different times recorded per commit, one
`CommitDate` and `AuthorDate`.
They can differ quite a lot when commits get rebased and merged from
branches i.e. So we include both times.
Mercurial doesn't differentiate in this afaik, which leads to an
empty `commit_info.author_time`.

Add commit_info.author_time

---

src/pytest_benchmark/hookspec.py

The hook calls and the specs used different parameter names for `pytest_benchmark_update_machine_info` and `pytest_benchmark_update_commit_info`, and pytest complained and failed when trying to override those hooks.
These commits fix the specs by changing the parameters names. Another approach would be to maintain the specs and change the hook calls, but it made more sense to change the parameter names in specs to maintain coherence with other hooks and with the parts of the code that call these hooks.
This pull request is made on top of https://github.com/ionelmc/pytest-benchmark/pull/73, so that one should be merged first.

Fix update hooks specs

---

AUTHORS.rst
CHANGELOG.rst
src/pytest_benchmark/utils.py

If the host system (or container) is missing programs like 'git' or 'hg', a FileNotFoundError is raised, which crashes the process. This patch adds this error to the list of continuable exceptions.
The tox tests pass against python3.5 & 2.7; waiting on Travis to verify the rest.
```bash
py35: commands succeeded
py27: commands succeeded
congratulations :)
```

Ignore FileNotFoundError when guessing project name.

---

src/pytest_benchmark/plugin.py
src/pytest_benchmark/stats.py

It should only be 10, based on https://github.com/ionelmc/pytest-benchmark/blob/ca13fbff602bf1cf169a035a900e8f765a587044/src/pytest_benchmark/plugin.py#L232.
cc @ionelmc

[cprofile] fix number of functions shown

---

.gitignore
.travis.yml
src/pytest_benchmark/logger.py
tests/test_benchmark.py
tox.ini

Since pytest 3.3 this plugin has been broken with `pytest -v`. This PR fixes that and enables testing on pytest 3.3.x/3.4.x/3.5.x.

Add support for pytest 3.3.x/3.4.x/3.5.x

---

AUTHORS.rst
CHANGELOG.rst
docs/comparing.rst

Following the discussion in Issue #102, it might be helpful to explicitly mention in the docs that for the default naming scheme to work that you should pass the `--benchmark-histogram` option last.
Checklist from [`CONTRIBUTING.md`](https://github.com/ionelmc/pytest-benchmark/blob/master/CONTRIBUTING.rst#pull-request-guidelines):

Add note in docs on passing --benchmark-histogram option last

---

CHANGELOG.rst

- This assumed that every instance of single tickmarks ([RST interpreted text ](http://docutils.sourceforge.net/docs/user/rst/quickref.html#contents)) was meant to be RST inline literal. If this is not the case (sorry) then these can be fixed as needed.

Fix formatting in CHANGELOG

---

docs/usage.rst
src/pytest_benchmark/plugin.py
src/pytest_benchmark/session.py
tests/test_benchmark.py

@ionelmc Hello again!
This allows:
```
[pytest]
addopts = --benchmark-skip
```
and one would only need to put `--benchmark-only` for the small subset of invocations/envs where you actually want to benchmark, eliminating `--benchmark-skip` everywhere else.

allow pytest to default to skip

---

docs/usage.rst
src/pytest_benchmark/plugin.py
tests/test_benchmark.py
tests/test_cli.py

Small fix for the help message, the `ops` column was missing from the list of default columns.

Update --columns help (missing ops)

---

src/pytest_benchmark/session.py

Hello,
very minor change that I noticed while looking at logs of a testuite of one of my projects. If pytest-benchmark is already disabled there should be no need of warning the user about that.
Best regards,
Francesco

Suppress warning on enabled xdist on or missing statistics dependency if the user had already asked --benchmark_disable

---

docs/usage.rst

Found out you could do this by reading the source.

Document multiple arguments to --benchmark-group-by

---

ci/appveyor-bootstrap.py
src/pytest_benchmark/utils.py

``flake8>=3.6.0`` produces following warnings on current master and it makes some ``pytest-benchmark`` ci tasks to fail:
```
$ flake8 src/ tests/ setup.py
src/pytest_benchmark/utils.py:113:39: F841 local variable 'exc' is assigned to but never used
src/pytest_benchmark/utils.py:285:45: W605 invalid escape sequence '\.'
src/pytest_benchmark/utils.py:583:6: W605 invalid escape sequence '\/'
```

Fix flake8 warnings

---

setup.py

Changes introduced by pytest 4.0 are breaking ones and require at least 3.6. Ref #129
Thanks, @ionelmc!

Require pytest>=3.6

---

src/pytest_benchmark/compat.py
src/pytest_benchmark/storage/file.py
tests/test_elasticsearch_storage.py
tests/test_storage.py

According to https://docs.python.org/3.3/library/functions.html#open :
"'U' universal newlines mode (for backwards compatibility; should not
be used in new code)"
To control how universal newlines works there is "newline" option.
So, to fix it is enough to remove "U" from a set of open options.
Fixes: https://github.com/ionelmc/pytest-benchmark/issues/137

Fix DeprecationWarning about 'U' open mode

---

src/pytest_benchmark/__init__.py

After calling pytest.main twice, pytest creates this `warning summary `
```bash
===================================================================== warnings summary =====================================================================
~/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:272
~/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:272: PytestWarning: Module already imported so cannot be rewritten: pytest_benchmark
self.config,
...
```
According to 
* https://github.com/pytest-dev/pytest/issues/2995
* https://github.com/pytest-dev/pytest-cov/pull/228/commits/22387a604ce8a082cc6381f1bbc28fa434c97bbe
the doc string `PYTEST_DONT_REWRITE` can be used to suppress this warning.

add PYTEST_DONT_REWRITE in order to suppress already imported warning

---

AUTHORS.rst
CHANGELOG.rst
docs/usage.rst
src/pytest_benchmark/session.py
src/pytest_benchmark/table.py
src/pytest_benchmark/utils.py
tests/test_cli.py
tox.ini

Related issues:
- #51 
- #106 (see https://github.com/ionelmc/pytest-benchmark/issues/106#issuecomment-450557882)

Report progress only if "--benchmark-verbose" is set

---

AUTHORS.rst
CHANGELOG.rst
src/pytest_benchmark/hookspec.py
src/pytest_benchmark/plugin.py

See
https://github.com/pytest-dev/pytest/pull/9118
https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
Closes #223

Use pytest.hookimpl/.hookspec to configure hooks

---

setup.py

This is needed since `py` is used but not explicitly listed. Pytest 7.2 no longer requires `py`, which breaks pytest-benchmark with this version of pytest.
Fixes #226

Add `py` to requirements

---

CHANGELOG.rst
CONTRIBUTING.rst

Tiny improvement to documentation. It's good to remove typos in code / cli arguments.

Fix typo and broken link

---

src/pytest_benchmark/compat.py
src/pytest_benchmark/utils.py

The `code` constructor has changed in Python 3.11. The PR adds the two new arguments.

Fix clonefunc() for Python 3.11

---

tests/test_benchmark.py

The code dump in PyTest has shorter context now. Removing the matching line is backwards compatible and fixes the test suite for the latest PyTest 7.4.2 release.

Adjust for shortened PyTest output

---

setup.py

Support for 3.8 was dropped in 15557b06a0564880e0abd1788b3c2033b8c68073, but this was left out.

remove 3.8 support from trove classifiers

---

src/pytest_benchmark/hookspec.py

The [hooks documentation](https://pytest-benchmark.readthedocs.io/en/latest/hooks.html) recommends using `pytest.mark.hookwrapper` to mark hook wrappers for `pytest_benchmark_generate_json` and `pytest_benchmark_group_stats` - which was deprecated in pytest-dev/pytest#9118.
The recommended approach is to use `@pytest.hookimpl(wrapper=True)`

Update docstrings to use preferred hookimpl decorator
